# Numpy Hands On

In [7]:
import numpy as np 

List takes everything as comma separated value, means it is not contiguous but Numpy array does not store comma separated values

In [8]:
num = np.array([1,2,3,4,5])
num2 = list([1,2,3,4,5])
print(num,num2,sep="\n")

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [9]:
n1 = np.array([5, 6])
n2 = np.array([7, 8])
n3 = list([1, 2])
n4 = list([4, 5])

print(n1*n2)
print(n1 + n2) # doing matrix operation
print(n3 * 2) # not mathematical

[35 48]
[12 14]
[1, 2, 1, 2]


In [10]:
# numpy turns every element according to the data type

a = np.array([1,2,3,'4'])
print(a)
# it turns all element to string 

['1' '2' '3' '4']


In [11]:
# it will take matrices form of n dimentional array 
b = np.array([[1,2],[3,4],[5,6]])
print(b)
# it will take matrices form of n dimentional array 
c = np.array([[1,2],[3,4],[5,6,1]])
print(c) 
# c will show error because all the dimention has to be same 

[[1 2]
 [3 4]
 [5 6]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## Data Type

In [21]:
a = np.array([1,2,3,4,5])
print(type(a))
print(type(a[0]))
a = np.array([[1,2,3,4,5],[6,"5",8,9,10]],dtype=int) 
# i can explicitly convert '5' to 5 but I couldn't turn any word to the integer
print(type(a[0][0]))



<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Slicing

In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1,2])
print(arr[1,2:])
print(arr[0,:3])
print(arr[1:,1:3])


7
[7 8]
[1 2 3]
[[ 6  7]
 [10 11]]


# inspection of array

In [22]:
 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(np.size(arr))
print(len(arr))
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.astype(float))


12
3
2
(3, 4)
int64
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


## Filling array

In [36]:
arr = np.full((2,2,2),8)
print(arr)
arr = np.zeros((3,3))
print(arr)
arr = np.ones((4,4))
print(arr)
# empty store the metadata not values 
arr = np.empty((2,2,2))
print(arr)
# arange is like range, make array from this to this
arr = np.arange(1,51,2)
print(arr)
# linspace is not like range, last input means proportion
arr = np.linspace(1,75,4)
print(arr)


[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[4.e-323 4.e-323]
  [4.e-323 4.e-323]]

 [[4.e-323 4.e-323]
  [4.e-323 4.e-323]]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 1.         25.66666667 50.33333333 75.        ]


## Mathematical Operation

In [41]:
# nan - if i dont give any number then i will fill nan in that place

arr = np.array([1,2,np.nan])
print(arr[2])

# if i divide anything with 0 it will give me infinity which can bring error so i can put np.inf their

print(np.array([10])/0)
# runtime warnig but provide inf 
# we can also use np.isinf and np.isnan to check 

nan
[inf]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_14376\1405857098.py:8: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [29]:
arr2 = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])
print(arr + arr2)
print(np.add(arr,arr2))
print(arr - arr2)
print(np.subtract(arr,arr2))
print(arr * arr2)
print(np.multiply(arr,arr2))
print(arr / arr2)
print(np.divide(arr,arr2))

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
print(np.power(arr,2))
print(np.sqrt(arr))

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


## concat and split

In [40]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[6, 7],
              [2, 9]])


print(a + b)  # it will do math operation

print(np.concatenate([a[0], b[1]]))

print(np.hstack([a[0], b[0]]))

print(np.vstack([a[0], b[0]]))

print(np.hstack([a, b]))

print(np.vstack([a, b]))

[[ 7  9]
 [ 5 13]]
[1 2 2 9]
[1 2 6 7]
[[1 2]
 [6 7]]
[[1 2 6 7]
 [3 4 2 9]]
[[1 2]
 [3 4]
 [6 7]
 [2 9]]


In [49]:
arr = np.array([1,2,3,4,5,6,7,8])

print(np.array_split(arr,4))
print(np.array_split(arr,5))
print(np.array_split(arr,9))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([], dtype=int64)]
