# **Numpy Hands On Practice** 👋


In [1]:
import numpy as np

List takes everything as comma separated value, means it is not contiguous but Numpy array does not store comma separated values


In [2]:
num = np.array([1, 2, 3, 4, 5])
num2 = list([1, 2, 3, 4, 5])
print(num, num2, sep="\n")

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [3]:
n1 = np.array([5, 6])
n2 = np.array([7, 8])
n3 = list([1, 2])
n4 = list([4, 5])

print(n1*n2)
print(n1 + n2)  # doing matrix operation
print(n3 * 2)  # not mathematical

[35 48]
[12 14]
[1, 2, 1, 2]


In [4]:
# numpy turns every element according to the data type

a = np.array([1, 2, 3, '4'])
print(a)
# it turns all element to string

['1' '2' '3' '4']


In [5]:
# it will take matrices form of n dimentional array
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)
# it will take matrices form of n dimentional array
c = np.array([[1, 2], [3, 4], [5, 6, 1]])
print(c)
# c will show error because all the dimention has to be same

[[1 2]
 [3 4]
 [5 6]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## Data Type


In [21]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(type(a[0]))
a = np.array([[1, 2, 3, 4, 5], [6, "5", 8, 9, 10]], dtype=int)
# i can explicitly convert '5' to 5 but I couldn't turn any word to the integer
print(type(a[0][0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Slicing


In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[1, 2])
print(arr[1, 2:])
print(arr[0, :3])
print(arr[1:, 1:3])

7
[7 8]
[1 2 3]
[[ 6  7]
 [10 11]]


# inspection of array


In [22]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(np.size(arr))
print(len(arr))
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.astype(float))

12
3
2
(3, 4)
int64
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


## Filling array


In [36]:
arr = np.full((2, 2, 2), 8)
print(arr)
arr = np.zeros((3, 3))
print(arr)
arr = np.ones((4, 4))
print(arr)
# empty store the metadata not values
arr = np.empty((2, 2, 2))
print(arr)
# arange is like range, make array from this to this
arr = np.arange(1, 51, 2)
print(arr)
# linspace is not like range, last input means proportion
arr = np.linspace(1, 75, 4)
print(arr)

[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[4.e-323 4.e-323]
  [4.e-323 4.e-323]]

 [[4.e-323 4.e-323]
  [4.e-323 4.e-323]]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 1.         25.66666667 50.33333333 75.        ]


## Mathematical Operation


In [41]:
# nan - if i dont give any number then i will fill nan in that place

arr = np.array([1, 2, np.nan])
print(arr[2])

# if i divide anything with 0 it will give me infinity which can bring error so i can put np.inf their

print(np.array([10]) / 0)
# runtime warnig but provide inf
# we can also use np.isinf and np.isnan to check

nan
[inf]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_14376\1405857098.py:8: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [29]:
arr2 = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])
print(arr + arr2)
print(np.add(arr, arr2))
print(arr - arr2)
print(np.subtract(arr, arr2))
print(arr * arr2)
print(np.multiply(arr, arr2))
print(arr / arr2)
print(np.divide(arr, arr2))

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
arr = np.arange(0, 91, 5)
print(np.sin(arr))
print(np.arctan(arr))
print(np.log(arr))

[ 0.         -0.95892427 -0.54402111  0.65028784  0.91294525 -0.13235175
 -0.98803162 -0.42818267  0.74511316  0.85090352 -0.26237485 -0.99975517
 -0.30481062  0.82682868  0.77389068 -0.38778164 -0.99388865 -0.17607562
  0.89399666]
[0.         1.37340077 1.47112767 1.50422816 1.52083793 1.53081764
 1.53747533 1.54223267 1.54580153 1.54857776 1.55079899 1.55261651
 1.5541312  1.55541293 1.55651158 1.55746378 1.55829698 1.55903216
 1.55968567]
[      -inf 1.60943791 2.30258509 2.7080502  2.99573227 3.21887582
 3.40119738 3.55534806 3.68887945 3.80666249 3.91202301 4.00733319
 4.09434456 4.17438727 4.24849524 4.31748811 4.38202663 4.44265126
 4.49980967]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_14376\731654517.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [33]:
print(np.power(arr, 2))
print(np.sqrt(arr))

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


## **concatenation**, **stacking**, and **splitting**

---

### **1. Concatenation in NumPy**
Concatenation combines two or more arrays along a specified axis.

#### Syntax:
```python
numpy.concatenate((array1, array2, ...), axis=0)
```

- `axis=0`: Combines along rows (vertically).
- `axis=1`: Combines along columns (horizontally).

#### Example:
```python
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
result_vertical = np.concatenate((array1, array2), axis=0)

# Concatenate along columns (axis=1)
result_horizontal = np.concatenate((array1, array2), axis=1)

print("Vertical Concatenation:\n", result_vertical)
print("Horizontal Concatenation:\n", result_horizontal)
```

---

### **2. Stacking in NumPy**
Stacking joins arrays along a new axis.

#### Functions:
- `numpy.stack`: Joins along a new axis.
- `numpy.vstack`: Stacks vertically.
- `numpy.hstack`: Stacks horizontally.
- `numpy.dstack`: Stacks depth-wise (along a new third axis).

#### Example:
```python
# Using the same arrays as before
# Stack along a new axis (axis=0)
stacked_new_axis = np.stack((array1, array2), axis=0)

# Vertical stack (no new axis)
vertical_stack = np.vstack((array1, array2))

# Horizontal stack (no new axis)
horizontal_stack = np.hstack((array1, array2))

print("Stacked along a new axis:\n", stacked_new_axis)
print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)
```

---

### **3. Splitting in NumPy**
Splitting divides an array into multiple sub-arrays.

#### Functions:
- `numpy.split`: Splits into specified equal parts.
- `numpy.vsplit`: Splits vertically.
- `numpy.hsplit`: Splits horizontally.

#### Example:
```python
# Creating a 2D array
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Split into 2 equal parts along columns (axis=1)
split_arrays = np.split(array, 2, axis=1)

# Vertical split into 2 parts (axis=0)
vertical_split = np.vsplit(array, 2)

print("Split into 2 equal parts:\n", split_arrays)
print("Vertical Split:\n", vertical_split)
```

---

### **Key Points**
1. **Concatenate** merges along an existing axis.
2. **Stack** adds a new axis while combining.
3. **Split** divides arrays into smaller sub-arrays.



In [40]:
a = np.array([[1, 2],
              [3, 4]])



b = np.array([[6, 7],
              [2, 9]])



print(a + b)  # it will do math operation



print(np.concatenate([a[0], b[1]]))



print(np.hstack([a[0], b[0]]))



print(np.vstack([a[0], b[0]]))



print(np.hstack([a, b]))



print(np.vstack([a, b]))

[[ 7  9]
 [ 5 13]]
[1 2 2 9]
[1 2 6 7]
[[1 2]
 [6 7]]
[[1 2 6 7]
 [3 4 2 9]]
[[1 2]
 [3 4]
 [6 7]
 [2 9]]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(np.array_split(arr, 4))
print(np.array_split(arr, 5))
print(np.array_split(arr, 9))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([], dtype=int64)]


## Insert


In [18]:
arr = np.array([1, 2, 3])
# np.insert(arr,2,90,axis=0) we can not do this like list , we have to save it in a new array or existing array to update it
arr = np.insert(arr, 2, 90, axis=0)
print(arr)
arr = np.insert(arr, [0, 1], [100, 200], axis=0)
# first it will insert 100 at 0 then 200 at index 1 , all the time it will look at the base array not the updated one, thats why it prints 100, 1, 200
print(arr)
arr = np.append(arr, [4, 5, 6], axis=0)
print(arr)
arr = np.full((2, 3, 3), 5)
# print(arr)
arr2 = np.insert(arr, 0, [6, 7, 8], axis=1)
print(arr2)

[ 1  2 90  3]
[100   1 200   2  90   3]
[100   1 200   2  90   3   4   5   6]
[[[6 7 8]
  [5 5 5]
  [5 5 5]
  [5 5 5]]

 [[6 7 8]
  [5 5 5]
  [5 5 5]
  [5 5 5]]]


# Delete


In [21]:
arr_base = np.random.randint(1, 10, (3, 3, 3))

[[[1 7 6]
  [8 1 1]
  [1 6 5]]

 [[5 5 3]
  [9 6 8]
  [3 2 7]]

 [[6 6 7]
  [3 4 1]
  [7 7 2]]]


`Understand AXIS`


In [30]:
arr = arr_base[:]
arr = np.delete(arr, 0, axis=0)
print(arr, end="\n\n")
arr = arr_base[:]
arr = np.delete(arr, 0, axis=1)
print(arr, end="\n\n")
arr = arr_base[:]
arr = np.delete(arr, 0, axis=2)
print(arr, end="\n\n")

[[[5 5 3]
  [9 6 8]
  [3 2 7]]

 [[6 6 7]
  [3 4 1]
  [7 7 2]]]

[[[8 1 1]
  [1 6 5]]

 [[9 6 8]
  [3 2 7]]

 [[3 4 1]
  [7 7 2]]]

[[[7 6]
  [1 1]
  [6 5]]

 [[5 3]
  [6 8]
  [2 7]]

 [[6 7]
  [4 1]
  [7 2]]]



In [33]:
arr_base = np.random.randint(1, 10, (2, 2, 2))
print(arr_base, end="\n\n")
arr = arr_base[:]
arr = np.delete(arr, 0, axis=0)
print(arr, end="\n\n")
arr = arr_base[:]
arr = np.delete(arr, 0, axis=1)
print(arr, end="\n\n")
arr = arr_base[:]
arr = np.delete(arr, 0, axis=2)
print(arr, end="\n\n")

[[[2 1]
  [3 9]]

 [[9 3]
  [2 9]]]

[[[9 3]
  [2 9]]]

[[[3 9]]

 [[2 9]]]

[[[1]
  [9]]

 [[3]
  [9]]]



## **Change Structure**

### **Comparison Table**

| Method       | Returns    | Changes Original? | Maintains Shape Rules | Copies Data? | Notes                                     |
|--------------|------------|-------------------|------------------------|--------------|-------------------------------------------|
| **reshape**  | New array  | No                | Yes                   | No (if possible) | Requires total elements to match.          |
| **resize**   | None       | Yes               | No                    | N/A          | Fills extra elements if resizing larger.  |
| **flatten**  | New array  | No                | N/A                   | Yes          | Always creates a copy.                    |
| **ravel**    | New array  | No                | N/A                   | No (if possible) | Returns a view if possible, else a copy.  |

---

### **Key Differences**
1. **reshape vs. resize**:
   - `reshape` creates a new array, while `resize` modifies the array in place.
   - `resize` allows changing the total number of elements, filling extras with default values, whereas `reshape` requires the same total number of elements.

2. **flatten vs. ravel**:
   - `flatten` always returns a copy, while `ravel` tries to return a view (more memory efficient).
   - Modifying a `ravel` result may affect the original array if it's a view.

---

In [34]:
arr = np.random.randint(1,10,(3,4))
print(arr)

[[2 2 6 8]
 [8 9 7 4]
 [2 6 4 1]]


In [45]:
arr1 = np.reshape(arr,(6,2)) 
# the multiply of axis must be same like 6*2, 4*3 , 12*1
print(arr1)

[[2 2]
 [6 8]
 [8 9]
 [7 4]
 [2 6]
 [4 1]]


In [46]:
arr.resize((4,3))
print(arr)

[[2 2 6]
 [8 8 9]
 [7 4 2]
 [6 4 1]]


In [49]:
arr2 = arr1.flatten()
print(arr2)

[2 2 6 8 8 9 7 4 2 6 4 1]


In [53]:
arr2 = np.ravel(arr1)
print(arr2)


[2 2 6 8 8 9 7 4 2 6 4 1]
[[2 2]
 [6 8]
 [8 9]
 [7 4]
 [2 6]
 [4 1]]
